<template>
 <v-container fluid>
      <h1> ---------------- CEMIS MENU (tests) --------------</h1>
      <v-card class="ma-2 pa-2">The Cemis menu is small, and difficult to navigate, and some stuff is hidden.
        This module is just a "View" of how full menu look. Press Ctrl-F in browser to search for a function, then logon to cemis yourself
        to check it out.</v-card>

      <ol><li v-for="(c,i) in tcem" :key="i" class="ma-2">
            <v-btn> {{ i+1 }}. {{ c.menu }}  </v-btn> {{ c.type }}
            <ol><li v-for="(l,j) in c.level" :key="j" style="list-style-type: lower-alpha;">
                 <v-btn color="primary" class="ma-2 pa-2" @click="cemisShow(c,l)" :title="l.desc"> {{ i+1 }}.{{ j+1 }}. {{ l.level }} </v-btn> {{ l.type }}
            <ol><li v-for="(m,k) in c.level.deeper" :key="k" style="list-style-type: lower-roman;">
                 <v-btn color="secondary" class="ma-2 pa-2" @click="cemisShow(c,m)" :title="m.desc"> {{ i+1 }}.{{ j+1 }}.{{ k+1 }}. {{ m.level }} </v-btn> {{ m.type }}
                </li>
            </ol>

                </li>
            </ol>
         </li>
      </ol>


<v-dialog v-model="showCemis">
<v-card>
    <v-card-text>
        {{ tcem }}   --------------- <br>{{ cemis }}
  </v-card-text>
  <v-card-actions>
  <v-spacer />
  <v-btn @click="showCemis = false"> close </v-btn>
  </v-card-actions>
 </v-card>
</v-dialog>

 </v-container>
</template>

<script>
import { zmlLog } from '@/api/zmlLog.js';
export default {
    name:"Cemis",
    computed: {
        tcem() {
            let all = []
            this.cemis.forEach(e => {
                let a = {}
                a.menu = e[0]
                a.type = 'top'  //typeof(e[2]) || ''
                a.level = []
                a.deeper = []
                 for (let i=2; i<12; i++) {
                    if (e[i]) {
                        //console.log('we have e' + i)
                        this.getit(a.level,e[i])

                        let deeper = e[i]
                        if (typeof(deeper) == 'object') {
                            a.level.deeper = []
                            //console.log('go deeper', e, deeper)
                            for (let j=2; j<12; j++) {
                                //console.log('Deeper[',j,']', deeper[j])
                                if (deeper[j]) {
                                   this.getit(a.level.deeper,deeper[j] )
                                   //console.log('fj-----' , deeper[j][0])
                                 }
                            }
                        }
                    } else  {
                        //console.log('missing' + i)
                    }
                 }

                all.push(a)
                //console.log(all)
            })
            console.log('all == ', all)
            return all
        }
    },
    methods: {
        cemisShow(x,y) {
            zmlLog(this.getZml.login.username || 'guest', 'CemisMenu',{x: x, y: y} )
            if (this.$superUser) {
                console.log('do ', x, y )
                this.showCemis = true
            }
        },
        getit(arr, obj) {
            let l = {}
            l.level = obj[0]
            l.desc = obj[1]
            l.type = '' //typeof(obj[2]) == 'undefined' ? '' : typeof(obj[2])
            arr.push(l)
        },
    },
    mounted() {

        console.log('cemis menu structure lookup')
    },
    watch: {
    },
    data: () => ({
        showCemis: false,
        rowid: 'C1C2AC44649445EF4DCD52D7BB921AE90D40F4E187977C5DDC157479FB50B72A',
        //fullAfter index 1 ?v_row_id=C1C2AC44649445EF4DCD52D7BB921AE90D40F4E187977C5DDC157479FB50B72A
        cemis: [
        ['LOG OFF', 'WEBPUB6.cm_gen_http_session.logout?row_id=15361267'],
        ['Learner Base', 'webpub6.CM_Learnertracking.STARTMSG',
                               ['New Registration ', 'WEBPUB6.cm_learner_TAB2007.home ' ],
                                ['UPDATE Learner', 'WEBPUB6.CM_LEARNER_BASE_UPDATE.SCHOOL_GRADES' ],
                                ['Upload', 'WEBPUB6.cm_Upload_Js.js_file_exist?row_id=15361267'],

                                ['New Registration ', 'webpub6.cm_learner_registration.register_new_learner ' ],
                                ['UPDATE Learner', 'webpub6.cm_learner_registration.select_grade ' ],
        ],
        ['Transfers', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Transfer In', 'WEBPUB6.CM_TRANSFER_IN.route_learnerfind' ],
                                ['Print Transfered ... In wys paar leerders per graad', 'webpub6.CM_TRANSIT_PRINT.GET_TRANSLEARNER' ],
                                ['Transfer Out / Exit', 'webpub6.CM_TRANSFER_OUT.GRADE_TRANS'],
                                ['Bulk Transfer-Out/Exit', 'webpub6.CM_TRANSFER_OUT.GRADE' ],
                                ['Cancel Transfer-Out/Exit', 'webpub6.CM_TRANSFER_OUT.GRADE_TRANS_undo' ],
                                ['Print Forms', 'webpub6.CM_TRANSFER_FORMS.SELECT_LETTER' ],
                                ['Bulk Print Forms', 'webpub6.CM_TRANSFER_OUT.select_grade' ],
        ],

        ['Classes Update', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Class Groups/LOLT', 'webpub6.cm_classes_new.class_count'],
                                ['Class Summary ... show teacher(admin) linked to class', 'webpub6.cm_classes_new.class_summary_report'],
                                ['Class Groups', 'WEBPUB6.cm_classes.CLASS_COUNT?row_id=15361267'],
                                ['Class LOLT', 'WEBPUB6.cm_class_LOLT.learner_grade?row_id=15361267'],
        ],


        ['Subjects/GET', 'webpub6.CM_Learnertracking.STARTMSG',
            ['Bulk Subj Allocation', 'WEBPUB6.Subject_allocation.selgade'],
            ['Learners Per Subject Gr10-12', 'webpub6.cm_subject_report.Subject_info ' ],
                                ['GET Bulk Update', 'WEBPUB6.cm_get_update.bulk_learner_grade'],
                                ['GET Learner Update', 'WEBPUB6.cm_get_update.learner_grade'],
                                ['Language Bulk Update', 'WEBPUB6.cm_language_update.bulk_learner_grade'],
                                ['Language Learner Update', 'WEBPUB6.cm_language_update.learner_grade'],
        ],

        ['School Dashboard', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Learner Information ... good for lots id info about student', 'webpub6.cm_cemis_menu.routing_wced_dashboard_learner'],
                                ['Educator Information', 'webpub6.cm_cemis_menu.routing_wced_dashboard_educ'],
                                ['Review Questionnaire', 'webpub6.cm_cemis_menu.routing_of_review_questions'],
        ],

        ['Reports', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Co-Morbidities and Other Indicators', 'WEBPUB6.cm_co_morbidities.co_morbidities_buttons ' ],
                                ['Learners', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Learner Control', 'WEBPUB6.CM_Learner_control.LEARNCONTROL ' ],
                                ['Learner Search', 'WEBPUB6.CM_LEARNER_REPORTS.select_letter ' ],
                                ['Learner Status', 'WEBPUB6.CM_REPORTS.LEARNER_GETSTATUS ' ],
                                ['Learners Per Type', 'WEBPUB6.CM_LEARNER_REPORTS2.LEARNERTYPE_INFO ' ],
                                ['Total Learners', 'WEBPUB6.cm_Leaners_per_School.load_learners ' ],
                                ['List Of Learners', 'WEBPUB6.CM_LEARNER_REPORTS.Learner_Grade ' ],
                                ['Learner Ages', 'WEBPUB6.CM_Learner_grade_ages_rpt.SCHOOL_GRADES ' ],
                                ['Underage Learner Report', 'webpub6.cm_underage_learners_report.select_grade?row_id=15361267' ],
                                ['Learner ID Numbers', 'WEBPUB6.CM_IDLIST_REPORT.gradelearnerlist ' ],
                                ['Extra Mural Activities', 'WEBPUB6.CM_LEARNER_REPORTS.ema_report_grade_sel ' ],
                                ['Hostel Boarder Report', 'webpub6.CM_HOSTEL_BORDER_REPORT.hostel_grade'],
                                ['Learner Cellphone/Email Report', 'webpub6.cm_learner_cellphone_report.learners_grade_list ' ],
                                ['Learner Parent Details', 'webpub6.cm_parent_info.parent_details_report ' ],
                                ['Learner Citizenship Report', 'webpub6.cm_lnr_citizenship_report.sa_immigrant_summary ' ],
        ],
        ['Subjects', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Registration Verification ', 'WEBPUB6.cm_Students_report_class.select_grade?row_id=15361267 ' ],
                                ['Subjects Per Learner ', 'WEBPUB6.cm_Students_report_class.selector ' ],
                                ['Learners Per Subject Gr10-12', 'webpub6.cm_subject_report.Subject_info ' ],
                                ['Music Instrument Report', 'WEBPUB6.CM_MUSIC_REPORT.learndetails' ],
                                ['Subject change request status', 'webpub6.Cm_cemis_menu.routing_subject_change' ],
                                ['Gr10 to 12 Bachelors Report', 'webpub6.cm_gr12_bachelors_report.bach_select_class' ],
                                ['Gr12 Learners not Qualifying for Bachelors', 'webpub6.cm_gr12_bachelors_report.bach_select_class?row_id=15361267' ],
        ],
        ['Disabilities', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Detailed Disabilities', 'webpub6.CM_disabilities_report.LEARNERS ' ],
                                ['Total Disabilities', 'webpub6.CM_LEARNER_REPORTS2.LEARNER_PRIMDIS_REPORT ' ],
        ],
        ['Languages', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Language Report', 'WEBPUB6.CM_LANGUAGE_REPORT.summary ' ],
                                ['GET Band Languages', 'WEBPUB6.CM_GETREPORT.learner_grade ' ],
                                ['LOLT Report', 'WEBPUB6.CM_LANG_TEACH_REPORT.summary ' ],
        ],
        ['Recording Sheets Gr1-9','webpub6.CM_Learnertracking.STARTMSG ',
                                ['Whats new 2017 Ver. 2', 'webpub6.CM_CEMIS_MENU.routing_recording_instructions?row_id=15361267'],
                                ['2017 Special Maths Condonation', 'webpub6.CM_CEMIS_MENU.routing_rec_math_condonation?row_id=15361267'],
                                ['Windows Fix', 'webpub6.CM_GRD1to9DOWNLOAD.windows_help?row_id=15361267'],
                                ['Gr7-9 Help', 'webpub6.CM_Cemis_Menu.routing_gr7_9_help?row_id=15361267'],
                                ['Gr1-9 Download', 'LEARNPERF.lpd_utl.not_available_msg'],
                                ['Gr1-9 Download', 'webpub6.CM_GRD1to9DOWNLOAD.selectgrade'],
                                ['Gr1-9 Upload Help', 'webpub6.CM_GRD1to9DOWNLOAD.guideline'],
                                ['Gr1-9 Upload', 'LEARNPERF.lpd_utl.selectgrade'],
                                ['Gr1-9 Upload Status', 'webpub6.cm_projects_status.gr1_9_upload_status'],
        ],
        ['Recording Sheets Gr10-12','webpub6.CM_Learnertracking.STARTMSG ',
                                 ['Gr12 Moderation Process', 'webpub6.cm_grd10_11_12_dwnld.guideline'],
                                 ['Gr10-12 Download', 'LEARNPERF.lpd_utl.not_available_msg'],
                                 ['Gr10-12 Download', 'webpub6.cm_grd10_11_12_dwnld.selectgrade'],
                                 ['Gr10-12 Upload', 'LEARNPERF.fet_utl.selectgrade'],
                                 ['Gr10-12 Upload Status', 'webpub6.cm_projects_status.gr10_12_upload_status'],
                                 ['Gr10-12 Subject Signoff', 'webpub6.cm_grd10_11_12_dwnld.sign_off_buttons'],
                                 ['Gr12 Moderation Marks View', 'webpub6.cm_term_performance_risk.sba_marks_view'],
        ],
        ['Error Reports', 'webpub6.CM_NEW_ERROR_REPORTS.MSG2 ' ],

        [ 'Promotions 2022', 'webpub6.CM_Learnertracking.startmsg ',
                                ['Promotion Summary', 'WEBPUB6.cm_promo_new.promo_summary_prev_year' ],
                                ['Promotion Report', 'webpub6.cm_promotion.grade_select_report' ],
                            ],
        ['Broadband Connectivity', 'webpub6.CM_Learnertracking.startmsg ',
                                ['Learner Login credentials', 'webpub6.cm_learner_credential.learner_credentials ' ],
                                ['Connection Introduction', 'webpub6.cm_learner_credential.connection_introduction ' ],
                                ['Guide', 'webpub6.cm_learner_credential.guide ' ],
                                ['Staff Request form', 'webpub6.cm_learner_credential.staff_request_form ' ],
                                ['Briefing Document', 'webpub6.cm_learner_credential.briefing_document ' ],
                                ['I.T. Helpdesk SOP', 'webpub6.Cm_cemis_menu.helpdesk_sop?row_id=15361267 ' ],
                                ['Educator/Admin Staff Login credentials', 'webpub6.cm_learner_credential.educator_credentials ' ],
        ],
        ['LMS', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',
                                ['Step-by-Step guide', 'webpub6.cm_lms.lms_guide?row_id=15361267 ' ],
                                ['Learner Login Details', 'webpub6.cm_lms.lms_report?row_id=15361267 ' ],
        ],
        ['Assessment Accommodations', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Manual', 'webpub6.cm_cemis_menu.routing_concess_adapt_manual?row_id=15361267'],
                                ['Contact details', 'webpub6.cm_barr_concess_adapt_report.contact_details'],
                                ['Apply for Accommodations', 'webpub6.cm_cemis_menu.routing_concession_adaptations'],
                                ['Delete an Application', 'webpub6.cm_cemis_menu.routing_del_concession_adapt?row_id=15361267'],
                                ['Accommodations Report', 'webpub6.cm_barr_concess_adapt_report.barrier_acc_buttons'],
                                ['Accommodations Letters','WEBPUB6.cm_cemis_menu.routing_accommodations_letters'],
                                ['Grade 12 Concessions Letters','WEBPUB6.cm_cemis_menu.routing_concession_letters'],
        ],

        ['Exam Center Audit Instrument', 'webpub6.exam_center_audit_instrument.exam_audit_instr_buttons',],
        ['Grade 3 Exemplars', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Language Exemplars', 'WEBPUB6.cm_exemplars.gr3_exemplars_literacy'],
                                ['Mathematics Exemplars', 'WEBPUB6.cm_exemplars.gr3_exemplars_numeracy'],
        ],
        ['Grade 6 Exemplars', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Language Exemplars', 'WEBPUB6.cm_exemplars.gr6_exemplars_language'],
                                ['Mathematics Exemplars', 'WEBPUB6.cm_exemplars.gr6_exemplars_mathematics'],
        ],
        ['Grade 9 Exemplars', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Language Exemplars', 'WEBPUB6.cm_exemplars.gr9_exemplars_language'],
                                ['Mathematics Exemplars', 'WEBPUB6.cm_exemplars.gr9_exemplars_mathematics'],
        ],
        ['Life Orientation Absenteeism', 'WEBPUB6.cm_meo_progressed.life_orientation_buttons'],
        ['MEO/Progressed', 'WEBPUB6.cm_meo_progressed.meo_prog_start_page'],
        ['NSC Exam Results', 'WEBPUB6.Cm_Cemis_Menu.routing_nsc_exam_results?row_id=15361267'],
        ['SOS Baseline', 'webpub6.CM_Learnertracking.STARTMSG ',
            ['Capture Screens', 'WEBPUB6.cm_gr_sos_competency.sos_grade_start'],
            ['Summary', 'WEBPUB6.cm_gr_sos_competency.sos_grade_summary_start'],
        ],
        ['Systemic Test Results 2022', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267',
                                ['GR3 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report&v_year=2022'],
                                ['GR3 Maths Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dm&v_year=2022'],
                                ['GR3 Lang Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dl&v_year=2022'],
                                ['GR6 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report&v_year=2022'],
                                ['GR6 Maths Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dm&v_year=2022'],
                                ['GR6 Lang Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dl&v_year=2022'],
                                ['GR9 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report&v_year=2022'],
                                ['GR9 Maths Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dm&v_year=2022'],
                                ['GR9 Lang Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dl&v_year=2022'],
        ],
        ['Systemic Test Results 2021', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267',
                                ['GR3 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report&v_year=2021'],
                                ['GR3 Maths Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dm&v_year=2021'],
                                ['GR3 Lang Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dl&v_year=2021'],
                                ['GR6 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report&v_year=2021'],
                                ['GR6 Maths Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dm&v_year=2021'],
                                ['GR6 Lang Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dl&v_year=2021'],
                                ['GR9 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report&v_year=2021'],
                                ['GR9 Maths Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dm&v_year=2021'],
                                ['GR9 Lang Item Analysis Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dl&v_year=2021'],
        ],
        ['Systemic Test Results 2019', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['GR3 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report&v_year=2019'],
                                ['GR3 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dm&v_year=2019'],
                                ['GR3 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dl&v_year=2019'],
                                ['GR6 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report&v_year=2019'],
                                ['GR6 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dm&v_year=2019'],
                                ['GR6 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dl&v_year=2019'],
                                ['GR9 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report&v_year=2019'],
                                ['GR9 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dm&v_year=2019'],
                                ['GR9 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dl&v_year=2019'],
        ],
        ['Systemic Test Results 2018', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['GR3 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report&v_year=2018'],
                                ['GR3 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dm&v_year=2018'],
                                ['GR3 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dl&v_year=2018'],
                                ['GR6 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report&v_year=2018'],
                                ['GR6 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dm&v_year=2018'],
                                ['GR6 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dl&v_year=2018'],
                                ['GR9 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report&v_year=2018'],
                                ['GR9 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dm&v_year=2018'],
                                ['GR9 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dl&v_year=2018'],
        ],
        ['Systemic Test Results 2017', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['GR3 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report&v_year=2017'],
                                ['GR3 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dm&v_year=2017'],
                                ['GR3 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr3_litnum_report_dl&v_year=2017'],
                                ['GR6 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report&v_year=2017'],
                                ['GR6 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dm&v_year=2017'],
                                ['GR6 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr6_litnum_report_dl&v_year=2017'],
                                ['GR9 Results', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report&v_year=2017'],
                                ['GR9 Maths Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dm&v_year=2017'],
                                ['GR9 Lang Diagnostic Report', 'WEBPUB6.Cm_Cemis_Menu.routing_gr9_litnum_report_dl&v_year=2017'],
        ],
        ['Systemic Tests 2023', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Notification Letter - Afr', 'WEBPUB6.cm_cemis_menu.routing_results_report_afr?row_id=15361267'],
                                ['Notification Letter - Eng', 'WEBPUB6.cm_cemis_menu.routing_results_report_eng?row_id=15361267'],
                                ['Learner Register 2023', 'WEBPUB6.cm_systemic_assessments.sys_select_grade_class?row_id=15361267'],
                                ['Learner Register Signoff', 'WEBPUB6.cm_systemic_assessments.sys_signoff?row_id=15361267'],
                                ['Principal Questionnaire', 'WEBPUB6.cm_systemic_assessments.sys_principal_questionnaire?row_id=15361267'],
        ],
        ['Systemic Test Results 2016', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Principal Letter', 'WEBPUB6.Cm_Cemis_Menu.systemic_principal_letter'],
                                ['Principal Letter - Afr', 'WEBPUB6.cm_cemis_menu.routing_results_report_afr?row_id=15361267'],
                                ['Principal Letter - Eng', 'WEBPUB6.cm_cemis_menu.routing_results_report_eng?row_id=15361267'],
                                ['GR3 Results 2016', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr3_litnum_2016'],
                                ['GR6 Results 2016 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr6_litnum_2016'],
                                ['GR9 Results 2016 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr9_litnum_2016'],
        ],
        ['Systemic Tests 2022', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Notification Letter - Afr', 'WEBPUB6.cm_cemis_menu.routing_results_report_afr?row_id=15361267'],
                                ['Notification Letter - Eng', 'WEBPUB6.cm_cemis_menu.routing_results_report_eng?row_id=15361267'],
                                ['Learner Register 2023', 'WEBPUB6.cm_systemic_assessments.sys_select_grade_class?row_id=15361267'],
                                ['Learner Register Signoff', 'WEBPUB6.cm_systemic_assessments.sys_signoff?row_id=15361267'],
                                ['Principal Questionnaire', 'WEBPUB6.cm_systemic_assessments.sys_principal_questionnaire?row_id=15361267'],
        ],
        ['Concessions/Adaptations', 'webpub6.cm_cemis_menu.routing_concession_adaptations?row_id=15361267'],
                            ['Concessions/Adaptations', 'webpub6.cm_cemis_menu.available_MSG?row_id=15361267'],
        ],
        ['ANA 2023', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267',
                                ['HL Report', 'WEBPUB6.cm_home_lang_report.grade_class_summary?row_id=15361267 ' ],
                                ['FAL Report', 'WEBPUB6.cm_first_add_lang_report.grade_class_summary?row_id=15361267 ' ],
                                ['LOLT Report', 'WEBPUB6.cm_lolt_lang_report.grade_class_summary?row_id=15361267 ' ],
                                ['SNE ANA Learners', 'webpub6.cm_sne_ana_learners.sne_ana_start?row_id=15361267' ],
                                ['ANA Printing Statistics', 'webpub6.cm_ana_requirements.ana_summary?row_id=15361267'],
                                ['ANA Mark Sheets Print', 'webpub6.cm_ana_testing_print.ana_select_grade?row_id=15361267'],

                                ['ANA Results', 'webpub6.cm_annual_results.results_report?row_id=15361267'],
                                ['ANA Parent Report', 'webpub6.cm_ana_testing_reports.ana_report_start?row_id=15361267'],
                                ['Mark Sheets Capture', 'webpub6.cm_ana_testing.ana_start1?row_id=15361267'],
                                ['Mark Sheets Capture', 'webpub6.cm_cemis_menu.available_MSG?row_id=15361267'],
                                ['View Captured Learners', 'webpub6.cm_ana_testing.ana_view_captured_learners?row_id=15361267'],
                                ['M/S Capture Signoff', 'webpub6.cm_ana_testing.ana_signoff?row_id=15361267'],
                                ['Print Mark Sheets', 'webpub6.cm_ana_testing_print.ana_select_grade?row_id=15361267'],
                                ['ANA Signoff Final', 'WEBPUB6.cm_ana_learner_registers.ana_learner_signoff_final?row_id=15361267 ' ],
                                ['Learner Registers', 'WEBPUB6.cm_ana_learner_registers.select_grade_class?row_id=15361267'],
                                ['ANA Signoff', 'WEBPUB6.cm_ana_learner_registers.ana_learner_signoff?row_id=15361267 ' ],
        ],
        ['Systemic Test Results 2015', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Principal Letter', 'WEBPUB6.Cm_Cemis_Menu.systemic_principal_letter'],
                                ['GR3 Results 2015', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr3_litnum_2015'],
                                ['GR6 Results 2015 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr6_litnum_2015'],
                                ['GR9 Results 2015 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr9_litnum_2015'],
        ],
        ['Systemic Test Results 2014', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Principal Letter', 'WEBPUB6.Cm_Cemis_Menu.systemic_principal_letter'],
                                ['GR3 Results 2014', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr3_litnum_2014'],
                                ['GR6 Results 2014 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr6_litnum_2014'],
                                ['GR9 Results 2014 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr9_litnum_2014'],
        ],
        ['Systemic Test Results 2013', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['GR3 Results 2013 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr3_litnum_2013?row_id=15361267'],
                                ['GR6 Results 2013 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr6_litnum_2013?row_id=15361267'],
                                ['GR9 Results 2013 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr9_litnum_2013?row_id=15361267'],
        ],
        ['Systemic Test Results 2012', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['GR3 Results 2012 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr3_litnum_2012?row_id=15361267'],
                                ['GR6 Results 2012 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr6_litnum_2012?row_id=15361267'],
                                ['GR9 Results 2012 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr9_litnum_2012?row_id=15361267'],
        ],
        ['Systemic Test Results 2011', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['GR3 Results 2011 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr3_litnum?row_id=15361267'],
                                ['GR6 Results 2011 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr6_litnum?row_id=15361267'],
                                ['GR9 Results 2011 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr9_litnum?row_id=15361267'],
        ],
        ['Systemic Test Results 2010', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['GR3 Results 2010 ', 'WEBPUB6.Cm_Cemis_Menu.routing_resultsGR3_report?row_id=15361267'],
                                ['GR6 Results 2010 ', 'WEBPUB6.Cm_Cemis_Menu.routing_resultsGR6_report?row_id=15361267'],
                                ['GR9 Results 2010 ', 'WEBPUB6.Cm_Cemis_Menu.routing_resultsGR9_report?row_id=15361267'],
        ],
        ['Term Performance', 'webpub6.cm_term_performance_1_9.tp_start' ,
                           ['LitNum Results 2009', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',['GR6 LitNum Result 2009 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report_gr6?row_id=15361267'],],
                           ['LitNum Results 2008', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',
                           ['GR3 LitNum Result 2008 ', 'WEBPUB6.Cm_Cemis_Menu.routing_Assessment_report?row_id=15361267'], ],
                           ['LitNum Results 2007', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',['GR6 LitNum Result 2007 ', 'WEBPUB6.Cm_Cemis_Menu.routing_report?row_id=15361267'],],
                           ['GR3 LitNum Test 2011 ', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',
                                ['Learner Registers 2011', 'WEBPUB6.CM_GRADE3_RESULTS.SCHOOL_CLASSES?row_id=15361267'],
                                ['Principal Questionnaires 2011', 'webpub6.CM_GRADE3_RESULTS.principal_questionaire?row_id=15361267'],
                                ['Notification Letter 2011', 'webpub6.CM_GRADE3_QUESTIONAIRE.cm_gr3_eval?row_id=15361267'],
                                ['Gr3 Sign-Off', 'WEBPUB6.CM_ASSESSMENT_SIGNOFF2010.grade_signoff3?row_id=15361267 ' ],
                           ],
                           ['GR6 LitNum Test 2011 ', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',
                                ['Learner Registers 2011', 'WEBPUB6.CM_GRADE6_RESULTS.SCHOOL_CLASSES?row_id=15361267'],
                                ['Principal Questionnaires', 'webpub6.CM_GRADE3_RESULTS.principal_questionaire?row_id=15361267'],
                                ['Notification Letter 2011', 'webpub6.CM_GRADE6_QUESTIONAIRE.cm_gr6_eval?row_id=15361267'],
                                ['Gr6 Sign-Off', 'WEBPUB6.CM_ASSESSMENT_SIGNOFF2010.grade_signoff6?row_id=15361267 ' ],
                           ],
                           ['GR9 LitNum Test 2011 ', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',
                                ['Learner Registers 2011', 'WEBPUB6.CM_GRADE9_RESULTS.SCHOOL_CLASSES?row_id=15361267'],
                                ['Principal Questionnaires', 'webpub6.CM_GRADE3_RESULTS.principal_questionaire?row_id=15361267'],
                                ['Notification Letter 2011', 'webpub6.CM_GRADE9_QUESTIONAIRE.cm_gr3_eval?row_id=15361267'],
                                ['Gr9 Sign-Off', 'WEBPUB6.CM_ASSESSMENT_SIGNOFF2010.grade_signoff9?row_id=15361267 ' ],
                           ],
                           ['Grade 1-6 Sign-Off', 'WEBPUB6.CM_ana_SIGNOFF.signoff?row_id=15361267' ],
                           ['Gr12 Data Signoff', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',
                                ['English document', 'webpub6.Cm_cemis_menu.Grade12_signoffENG?row_id=15361267'],
                                ['Afrikaans document', 'webpub6.Cm_cemis_menu.Grade12_signoffAFR?row_id=15361267'],
                           ],
        ],
        ['Surveys', 'webpub6.CM_Learnertracking.STARTMSG',
                            ['Snap Survey 2023', 'webpub6.CM_Learnertracking.STARTMSG ',
                                    ['Survey Guideline', 'SNAP2007.cm_snap_ord_capture.survey_guideline?row_id=15361267 '],
                                    ['Progress Report', 'SNAP2007.snap_progress_report.progress_report ' ],
                                    ['Capture Screens', 'SNAP2007.cm_snap_ord_capture.MSG8 ' ],
                                    ['Error Reports', 'SNAP2007.cm_snap_error_reports.snap_start ' ],
                                    ['Display Reports', 'snap2007.cm_snap_ord_display.ord_msg ' ],
                                    ['Survey Signoff', 'SNAP2007.cm_snap_ord_sign_off.sign_off_new ' ],
                                    ['List of Educators', 'ass2007.cm_educator_information.snap_report_of_educators ' ],
                                    ['Educator Display Reports', 'ass2007.cm_educator_display_reports.educ_display_report_start ' ],
                            ],
                            ['Annual 2023', 'ass2007.cm_ass_capture.survey_closed?row_id=15361267 ' ],
                            ['Annual 2023', 'webpub6.Cm_Learnertracking.STARTMSG ',
                                ['Survey Message', 'ass2007.cm_ass_capture.survey_msg?row_id=15361267 ' ],
                                ['Progress Report', 'ass2007.cm_ord_progress.ass_progress_report ' ],
                                ['Capture Screens', 'ass2007.cm_ass_capture.msg '],
                                ['Error Reports', 'ass2007.cm_ord_ass_error_reports.msg2 ' ],
                                ['Display Reports', 'ass2007.cm_ord_ass_display_reports.ord_msg ' ],
                                ['Educator Survey Form', 'webpub6.cm_cemis_menu.routing_of_educator_form?row_id=15361267 ' ],
                                ['Add/Capture Educator', 'ass2007.cm_educator_information.educator_login ' ],
                                ['List of Educators', 'ass2007.cm_educator_information.ass_report_of_educators ' ],
                                ['Educator Error Reports', 'ass2007.cm_educator_error_reports.educ_err_rep_start ' ],
                                ['Educator Display Reports', 'ass2007.cm_educator_display_reports.educ_display_report_start ' ],
                                ['Annual Signoff', 'ass2007.cm_ass_ord_sign_off.sign_off_new ' ],
                                ['Educator Progress Report', 'ass2007.cm_educator_error_reports.educ_progress_report ' ],
                                ['Educator Signoff', 'ass2007.cm_educator_signoff.educ_sign_off ' ],
                            ],
        ],
        ['Educator Information', 'webpub6.Cm_Learnertracking.STARTMSG',
                            ['Educator Survey Form', 'webpub6.cm_cemis_menu.routing_of_educator_form ' ],
                            ['List of Educators', 'ass2007.cm_educator_information.ass_report_of_educators ' ],
                            ['Add/Capture Educator', 'ass2007.cm_educator_information.educator_login ' ],
                            ['Educator Error Reports', 'ass2007.cm_educator_error_reports.educ_err_rep_start ' ],
                            ['Educator Display Reports', 'ass2007.cm_educator_display_reports.educ_display_report_start ' ],
                            ['Educator Sign-Off', 'ass2007.cm_educator_signoff.educ_sign_off?row_id=15361267 ' ],
        ],
        ['Administration', 'webpub6.Cm_Learnertracking.STARTMSG',
                        ['Annual Academic Performance Report','webpub6.cm_aapr.aapr_buttons'],
                        ['BEEI', 'webpub6.CM_Learnertracking.STARTMSG?row_id=15361267 ',
                              ['BEEI 2021/2022', 'webpub6.cm_cemis_menu.routing_beei_letter?row_id=15361267&v_year=2021'],
                        ],
                        ['Educators Vaccination Roll out','webpub6.cm_educ_vaccination_rollout.vaccination_buttons'],
                        ['Additional Posts', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Apply for Additional Post',     'webpub6.cm_cemis_menu.routing_additionalpost_apply?row_id=15361267'],
                                ['Delete the application', 'webpub6.cm_cemis_menu.routing_curriculum_delete?row_id=15361267'],
                                ['View status of application', 'webpub6.cm_cemis_menu.routing_curriculum_view'],
                                ['Apply for Additional Post',     'WEBPUB6.Cm_cemis_menu.route_Aplication?row_id=15361267'],
                        ],
                        ['Caps Textbook Topup', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Welcome and Guidelines','webpub6.cm_caps_orders_topup.get_guidelines'],
                                ['How To guide','webpub6.cm_caps_orders_topup.get_howtoguide'],
                                ['Addendum 1','webpub6.cm_caps_orders_topup.get_template'],
                                ['View Previous Textbooks Ordered','webpub6.cm_caps_orders_topup.view_catalogue'],
                                ['Capture Screens','webpub6.cm_caps_orders_topup.caps_topups_application'],
                                ['Confirmation Letter','webpub6.cm_caps_orders_topup.confirmation_letter?row_id=15361267'],
                        ],
                        ['COVID-19 Monitoring Tool','webpub6.cm_covid19_sim_tool.sim_select_grade'],
                           ['Cust Satisfaction Survey','WEBPUB6.cm_customer_survey.cust_select_educ_type?row_id=15361267'],
                           ['EMIS Officer', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['EMIS Letter', 'WEBPUB6.cm_emis_officer.emis_letter'],
                                ['EMIS Officer Role', 'webpub6.cm_emis_officer.emis_officer_role'],
                                ['EMIS Signoff', 'webpub6.cm_emis_officer.emis_signoff'],
                           ],
                          ['Establishments', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Establishment 2023', 'webpub6.cm_cemis_menu.routing_staff_estab_letter_e&v_year=2022'],
                                ['Establishment 2022', 'webpub6.cm_cemis_menu.routing_staff_estab_letter_e&v_year=2021'],
                          ],
                          ['Establisments - Public Service', 'webpub6.CM_Learnertracking.STARTMSG ',
                            ['Establishment 2022', 'webpub6.cm_cemis_menu.routing_staff_estab_letter_ps&v_year=2021'],
                            ['Establishment 2021', 'webpub6.cm_cemis_menu.routing_staff_estab_letter_ps&v_year=2020'],
                          ],
                          ['Equipment Allocation', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Guidelines',     'WEBPUB6.Cm_cemis_menu.routing_guidelines?row_id=15361267'],
                                ['Letter',     'WEBPUB6.cm_equipment_letters.letter?row_id=15361267'],
                                ['Letter - English',  'WEBPUB6.cm_telecom_letters.admin_refresh_letter_eng'],
                                ['Letter - Afrikaans',  'WEBPUB6.cm_telecom_letters.admin_refresh_letter_afr?row_id=15361267'],
                                ['Letter - isiXhosa',  'WEBPUB6.cm_telecom_letters.admin_refresh_letter_xho?row_id=15361267'],
                                ['Excel Template',     'WEBPUB6.Cm_cemis_menu.routing_excel_equip?row_id=15361267'],
                          ],
                          ['General Information', 'webpub6.cm_cemis_geninfo_tab.home'],
                            ['Grade changes', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['School Correction',     'WEBPUB6.Cm_Learner_Grade_Change.Get_id'],
                                ['Grade Change Manual', 'WEBPUB6.cm_cemis_menu.routingExams'],
                                ['Capture Request', 'WEBPUB6.cm_cemis_menu.routingemdc'],
                                ['Cancel Request', 'WEBPUB6.cm_cemis_menu.routingExams1'],
                            ],
                            ['Grade R Subsidy', 'webpub6.CM_Learnertracking.STARTMSG',
                               ['Manual', 'webpub6.cm_GrR_subsidy.grade_R_subsidy_manual'],
                               ['Submit Application', 'webpub6.cm_GrR_subsidy.grade_R_available'],
                               ['Submit Application', 'webpub6.cm_GrR_subsidy.application_yn'],
                               ['Claim Status', 'webpub6.cm_GrR_subsidy.subsidy_claim_status1'],
                               ['Subsidy Payment Letter', 'webpub6.cm_GrR_subsidy.subsidy_claim_letter'],
                            ],
                            ['Learner Transport', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['IRS Minute 0010/2014', 'webpub6.cm_cemis_menu.routing_of_lts_irs_minute?row_id=15361267'],
                                ['LTS Guide', 'webpub6.cm_cemis_menu.routing_of_lts_guide?row_id=15361267'],
                                ['LTS Guide', 'webpub6.cm_cemis_menu.routing_of_lts_guide?row_id=C1C2AC44649445EF4DCD52D7BB921AE90D40F4E187977C5DDC157479FB50B72A'],
                                ['Capture Screens', 'webpub6.cm_lts.lts_select_grade?row_id=15361267'],
                                ['Capture Screens', 'webpub6.cm_lts.lts_select_grade?row_id=C1C2AC44649445EF4DCD52D7BB921AE90D40F4E187977C5DDC157479FB50B72A'],
                            ],
                            ['Norms and Standards Allocation', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['N & S 2023/24 Final', 'webpub6.CM_norms_standards2022.letter_revised_start?row_id=15361267'],
                                ['N & S 2023/24', 'webpub6.CM_norms_standards2022.letter_start?row_id=15361267'],
                                ['N & S 2022/23 Final', 'webpub6.CM_norms_standards2021.letter_revised_start'],
                            ],
                            ['School Emergency Maintenance', 'webpub6.cm_learnertracking.startmsg?row_id=15361267',
                                ['Manual', 'webpub6.cm_sefmis.sefmis_manual?row_id=15361267'],
                                ['Manual', 'webpub6.cm_sefmis.sefmis_manual?row_id=C1C2AC44649445EF4DCD52D7BB921AE90D40F4E187977C5DDC157479FB50B72A'],
                                ['Submit Request', 'webpub6.cm_sefmis.sefmis_start?row_id=15361267'],
                                ['Submit Request', 'webpub6.cm_sefmis.sefmis_start?row_id=C1C2AC44649445EF4DCD52D7BB921AE90D40F4E187977C5DDC157479FB50B72A'],
                            ],
                            ['School Enrichment Programmes', 'webpub6.cm_learnertracking.startmsg',
                                ['Manual', 'webpub6.cm_seps.seps_manual'],
                                ['Capture Screens', 'webpub6.cm_seps.seps_start'],
                                ['Register Coach/Facilitator', 'webpub6.cm_seps.register_coach'],
                            ],
                            ['School Fee Exemption', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Guidelines', 'webpub6.cm_fee_exemption.fee_exemption_guidelines'],
                                ['Capture Screens', 'webpub6.cm_fee_exemption.fee_application'],
                                ['Fee Exemption Signoff', 'webpub6.cm_fee_exemption.fee_signoff'],
                                ['Fee Exemption Letter', 'WEBPUB6.cm_fee_exemption_letter.letter'],
                            ],
                            ['School Governing Body (SGB)', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Manual', 'webpub6.cm_sgb_new.routing_of_sgb_voters_roll_man'],
                                ['Rating Descriptors', 'webpub6.cm_sgb_new.view_rating_descriptors'],
                                ['Capture Screens', 'webpub6.cm_sgb_new.sgb_start'],
                            ],
                            ['School Improvement Monitoring', 'webpub6.CM_Learnertracking.STARTMSG',
                                 ['Document', 'webpub6.cm_SIM_new.sim_documents'],
                                 ['Term 1 - Executive Summary', 'webpub6.cm_SIM_new.routing_of_sim_summary'],
                                 ['Capture Screen', 'webpub6.cm_SIM_new.sim_home'],
                            ],
                            ['School Self-Evaluation', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Template', 'webpub6.cm_school_self_evaluation.routing_of_sse_template'],
                                ['Capture Screens', 'webpub6.cm_school_self_evaluation.sse_buttons'],
                            ],
                            ['Stationery/Cleaning Order', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Welcome and Guideline', 'webpub6.cm_stat_clean_ordering.routing_of_stat_clean_welcome'],
                                ['Manual', 'webpub6.cm_stat_clean_ordering.routing_of_stat_clean_manual'],
                                ['Capture Order', 'webpub6.cm_stat_clean_ordering.stat_and_clean_application'],
                                ['Confirmation Letter', 'webpub6.cm_stat_clean_ordering.stat_clean_letter'],
                            ],
                            ['Subjects Principal Signoff', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Gr12 Subjects', 'webpub6.cm_cemis_subjects_signoff.gr12_signoff'],
                                ['Gr11 Subjects', 'webpub6.cm_cemis_subjects_signoff.gr11_signoff'],
                                ['Gr10 Subjects', 'webpub6.cm_cemis_subjects_signoff.gr10_signoff'],
                            ],
                            ['Telecommunications Allocation', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Guideline',  'WEBPUB6.Cm_cemis_menu.routing_guide_tele'],
                                ['Telecommunications Allocation',  'WEBPUB6.cm_telecom_letters.letter'],
                                ['Excel Template',     'WEBPUB6.cm_telecom_letters.excel_tele'],
                            ],
                            ['Textbook Issued/Retrievals', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Capture 2023','webpub6.cm_textbook_retrieval.select_textbook_buttons'],
                                ['Capture 2022','webpub6.cm_textbook_retrieval.select_textbook_buttons1'],
                            ],
                            ['Transfer Payments', 'WEBPUB6.cm_transfer_payments.view_transfer_payments'],
                            ['Workbooks', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Welcome', 'webpub6.cm_workbooks.wb_welcome'],
                                ['How To Guide', 'webpub6.cm_workbooks.wb_how_to_guide'],
                                ['Capture Screens', 'webpub6.cm_workbooks.wb_start'],
                                ['Capture Screens', 'webpub6.cm_workbooks.wb_not_available?row_id=15361267'],
                                ['Workbook Orders', 'WEBPUB6.cm_workbook_orders.select_workbook_phase?row_id=15361267'],
                                ['Workbook Shortages', 'WEBPUB6.cm_workbook_orders.select_workbook_ph_shortages?row_id=15361267'],
                            ],
        ],
        ['Absenteeism/Screening', 'webpub6.CM_Learnertracking.STARTMSG ',
                            ['Capture Learner Screening', 'webpub6.cm_cemis_menu.capture_lnr_screening'],
                            ['Learners Not Screened', 'webpub6.cm_learners_not_screened.not_screened_buttons ' ],
                            ['Capture absenteeism', 'webpub6.cm_cemis_menu.capture_absenteeism'],
                            ['Capture absenteeism', 'webpub6.cm_cemis_menu.available_MSG'],
                            ['View Capture Status', 'webpub6.cm_cemis_menu.view_status_absenteeism'],
                            ['Reset password', 'webpub6.cm_admin_support.reset_absenteeism_password'],
                            ['Register LACs', 'webpub6.cm_admin_support.admin_support_start_page'],
                            ['Capture school holidays', 'webpub6.cm_school_holidays.cm_school_holidays_capture?row_id=15361267'],
                            ['Capture school holidays extended', 'webpub6.cm_school_holidays.cm_school_holidays_capture_ext'],
                            ['Capture school days (COVID19)', 'webpub6.CM_Learnertracking.STARTMSG ',
                                ['Capture 2023', 'webpub6.cm_school_holidays.covid19_school_days_capture'],
                                ['Capture 2022', 'webpub6.cm_school_holidays.covid19_school_days_capture1'],
                            ],
                            ['View Print Register', 'webpub6.cm_cemis_menu.view_print_reg_absenteeism'],
                            ['View Summary Register', 'webpub6.cm_cemis_menu.view_summary_reg_absenteeism'],
                            ['Monthly Absenteeism', 'WEBPUB6.plpdf_helloworld?row_id=15361267'],
                            ['QLAR differences', 'webpub6.cm_learners_not_screened.lnr_screen_totals'],
                            ['Quarterly Learner Absenteeism', 'webpub6.CM_Learnertracking.STARTMSG',
                                ['Quarterly absenteeism 2023', 'webpub6.cm_quartley_attendance_tab2023.home'],
                                ['Quarterly absenteeism 2022', 'webpub6.cm_quartley_attendance_tab2022.home'],
                            ],
        ],
        ['Learner Admin Search', 'webpub6.cm_learner_search.learner_cemis_search'],
        ['CEMIS Support', 'webpub6.CM_Learnertracking.STARTMSG ',
                            ['District Contact details', 'webpub6.cm_modules_contact.district_contact_details'],
                            ['Capture Screens Contact details', 'webpub6.cm_modules_contact.contact_details'],
                            ['Web Settings - IE9', 'webpub6.Cm_cemis_menu.routing_cemis_settings'],
                            ['Web Settings - IE10', 'webpub6.Cm_cemis_menu.routing_cemis_settings_v10'],
                            ['Web Settings - IE11', 'webpub6.Cm_cemis_menu.routing_cemis_settings_v11'],
        ],
        ['Admissions', 'webpub6.CM_Learnertracking.STARTMSG',
                        ['Capture Online Admissions', 'webpub6.Cm_cemis_menu.routing_online_admissions'],
                               ['Planned Enrolment Status', 'webpub6.CM_Learnertracking.STARTMSG',
                                  ['Planned Template','WEBPUB6.cm_sami.sami_template'],
                                  ['Reports','WEBPUB6.cm_sami.sami_start'],
                                  ['Multiple Acceptances', 'WEBPUB6.cm_sami.sami_multiple_app?row_id=15361267'],
                                  ['Confirmation of Learner Enrolment', 'WEBPUB6.cm_sami.sami_success_learners?row_id=15361267'],
                               ],
                               ['View Online Applications','WEBPUB6.cm_sami.sami_start'],
        ],
  ]

    }),
}
</script>