export const extNames = [
  {'audio': ['aif',   'cda', 'mid', 'midi',  'mpa', 'wma', 'wpl']},
  {'audio-playable': ['mp3', 'ogg', 'wav']},
  {'archive': ['7z', 'arj', 'deb', 'pkg', 'rar', 'rpm', 'tar.gz', 'z', 'zip']},
  {'disc': ['dmg', 'iso', 'toast', 'vcd',  ]},
  {'database': [    'csv', 'dat', 'db', 'dbf', 'log', 'mdb', 'sav', 'sql', 'tar'  ]},
  {'executable': ['apk', 'bat', 'bin', 'cgi', 'pl', 'com', 'exe', 'gadget', 'jar', 'py', 'wsf', 'ipa']},
  {'font': ['fnt', 'fon', 'otf', 'ttf']},
  {'image': ['ai', 'bmp', 'gif', 'ico', 'jpeg', 'jpg', 'png', 'ps', 'psd', 'svg', 'tif', 'tiff']},
  {'markup': ['asp', 'aspx', 'cer', 'cfm', 'cgi', 'pl', 'css', 'scss', 'htm',
            'html', 'jsp', 'part', 'php', 'py', 'rss', 'xml', 'shtml', 'xhtml'  ]},
  {'link': ['link','zlink','test']},
  {'presentation': ['key', 'odp', 'pps', 'ppt','pptm', 'pptx']},
  {'script': ['c', 'class', 'cpp', 'cs', 'h', 'java', 'js', 'json', 'sh', 'swift', 'vb']},
  {'sheet': ['ods', 'xlr', 'xls', 'xlsx']},
  {'system': [    'bak', 'cab', 'cfg', 'cpl', 'cur', 'dll', 'dmp', 'drv', 'icns',
                 'ini', 'lnk', 'msi', 'sys', 'tmp'  ]},
  {'video': [ '3g2', '3gp', 'avi', 'flv', 'h264', 'mkv', 'mpg', 'mpeg', 'rm',
             'swf', 'vob', 'wmv',  ]},
  {'video-playable': ['mp4', 'webm', 'mov','mkv','avi']},
  {'vue': ['vue']},
  {'doc': ['doc', 'docx', 'odt', 'rtf', 'tex', 'wks', 'wps', 'wpd',  ]},
  {'text': ['txt']},
  {'ebook': ['epub']},
  {'pdf': ['pdf']},
  {'folder': ['folder']},
  {'play': ['play']},
]

export const fileTypes = [
    {type: 'audio', color:'blue', icon:'mdi-file-music'},
    {type: 'audio-playable', color:'blue',icon:'mdi-music-note'},
    {type: 'archive', color:'yellow', icon:'mdi-folder-zip'},
    {type: 'disc', color:'silver', icon:'mdi-disc'},
    {type: 'database', color:'lightblue', icon:'mdi-database'},
    {type: 'executable', color:'red', icon:'mdi-application'},
    {type: 'font', color:'orange', icon:'mdi-font'},
    {type: 'image', color:'blue', icon:'mdi-image'},
    {type: 'markup', color:'purple', icon:'mdi-marker'},
    {type: 'presentation', color:'', icon:'mdi-presentation'},
    {type: 'script', color:'green', icon:'mdi-script'},
    {type: 'sheet', color:'green darken-1', icon:'mdi-file-excel'},
    {type: 'system', color:'black', icon:'mdi-link-box'},
    {type: 'video', color:'indigo lighten-1', icon:'mdi-movie'},
    {type: 'video-playable', color:'indigo darken-1', icon:'mdi-movie'},
    {type: 'vue', color:'blue', icon:'mdi-screw-lag"'},
    {type: 'doc', color:'blue', icon:'mdi-file-document'},
    {type: 'text', color:'blue darken-1', icon:'mdi-text'},
    {type: 'ebook', color:'orange', icon:'mdi-text-subject'},
    {type: 'pdf', color:'red darken-1', icon:'mdi-file-pdf-box'},
    {type: 'folder', color:'yellow darken-2', icon:'mdi-folder'},
    {type: 'play', color:'gold', icon:'mdi-golf'},
    {type: 'link', color: 'purple', icon: 'mdi-link'}
  ]
