export const en = {
    btn: {
        home: "HOME",
        tiphome: "HOME",
        about : "ABOUT",
        tipabout : "More about about",
        viewcats: "Learn",
        tipviewcats: "View Categories",
        teacher: "Teachers",
        tipteacher: "Change data",
        tHover : "Hover",
        tiptHover : "test some hover funcs",
        translate : "TRANSLATE",
        tiptranslate : "test some trasnlation functions",        
        help : "HELP",
        tiphelp : "More about help",
        changeTo : "Change To - Afr",
        tipchangeTo : "Click here to change to Afrikaans",
        rightmenubutton: "menu",
        Login: "Login",
        tipLogin: "Tip for Login",
        Profile: "Profile",
        tipProfile: "Tip for Profile",
        Logout: "Logout",
        tipLogout: "Tip for Logout",
        modal: "toestModal",
        tipmodal: "toets gou nested .. Modal",
        testsConfirm: "confirm",
        tiptestsConfirm: "test our DialogConformModel",
    },
    message: {
      programname: "DK Online Resources",
      ZMLContactFormHeading: "DK Online Resources Contact Form",
      CanceltheEmail: "Cancel the Email",
      SubmityourEmail: "Submit the Email",
      LoginHeading: "Login",
      hello: 'hello world',
      greeting: (ctx) => `hello, ${ctx.named('name')}!`,
      leeting: (x) => `hello (name), ${x.list(0)}!`,
      nested:{
          binnein: "this is inside",
      },
    donner: 'oh no!',
    Delete:"Delete",
    AreYouSure:"Are you sure?",
    },
      computed: {
        nickName () { return 'Werner' }
    },
    data: { greet: 'hello' }
}

export const af = {
    btn: {
        home: "HUIS",
        tiphome: "HUIS",
        about : "OOR ONS",
        tipabout : "Meer oor ons",
        viewcats: "Leer",
        tipviewcats: "VBekyk Categories",
        teacher: "Onnies",
        tipteacher: "Verander data",
        tHover : "HANGOOR",
        tiptHover : "toets v-hover funcksie",
        translate : "VERTAAL",
        tiptranslate : "Toets vertaal funksies",                
        help : "HULP",
        tiphelp : "Meer oor help",
        changeTo : "Verander na - Engels",
        tipchangeTo : "Kliek hier om alles in engels te sien",
        rightmenubutton: "kieslys",
        Login: "Teken Aam",
        tipLogin: "Tip for Login",
        Profile: "Profiel",
        tipProfile: "Tip for Profile",
        Logout: "Teken Uit",
        tipLogout: "Tip for Uitteken",
        modal: "toestModal",
        tipmodal: "toets gou nested .. Modal",
        testsConfirm: "maakseker",
        tiptestsConfirm: "toets ons DialogConfirmModel",
    },
    message: {
        programname: "DK Aanlyn Hulpbronne",
        ZMLContactFormHeading: "DK Hulpbron Kontak Vorm",
        CanceltheEmail: "Kanselleer die briefie",
        SubmityourEmail: "Stuur die brief",
        LoginHeading: "Meld Aan",
        hello: 'hallo wereld',
        greeting: (ctx) => `dagsê, ${ctx.named('name')}!`,
        leeting: (x) => `dagsê (naam), ${x.list(0)}!`,
         nested:{
          binnein: "hirsie is binnein",
        },
        donner: 'agge nee!',
        Delete:"Vee Uit",
        AreYouSure:"Is jy seker?",
      },
    computed: {
        nickName () { return 'Werner' },
    },
      data: { greet: 'hello' },
}