R:\Develop\NodeDev\real\fresh\src\components\Kalender.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\buttons.js.bak
R:\Develop\NodeDev\real\fresh\src\tmp\constants.js.bak
R:\Develop\NodeDev\real\fresh\src\tmp\ContactForm.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\Calendar.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\EmailBulletins.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\MeritChip.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\MeritStepper.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\PersonelNameList.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\PersonelNamePicture.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\StudentPhotoList.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\skool.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\AppLayoutLinks.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\AppLayoutGray.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\index.js.beforebigchanges.bak
R:\Develop\NodeDev\real\fresh\src\tmp\vuetify.js.bak
R:\Develop\NodeDev\real\fresh\src\tmp\s.s.bak
R:\Develop\NodeDev\real\fresh\src\tmp\chunks.bak
R:\Develop\NodeDev\real\fresh\src\tmp\PersonelInfo.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\zGetBackgroundData.js.bak
R:\Develop\NodeDev\real\fresh\src\tmp\ViewFunctions.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\vFormBase.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\baseSearch.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\index.js.bak
R:\Develop\NodeDev\real\fresh\src\tmp\ListTestButtons.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\HomeStart.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\MeritStart.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\baseTool.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\zmlPreview.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\PersonelEdit.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\TeacherClassList.vue.bak
R:\Develop\NodeDev\real\fresh\src\tmp\AutoSelRoom.vue.bak
